version: '3.9'
services:
  mysql:
    image: mysql
    env_file: "./.env"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "plura-db:/var/lib/mysql"

volumes:
  plura-db:
  
    